//
//  MainFeedModels.swift
//  PantipFeed
//
//  Created by thanathip.kumnarai on 18/7/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainFeed {
    // MARK: Use cases
    
    enum GetTopicData {
        struct Request {
            
        }
        
        struct Response {
            let topicsResponse: TopicList?
        }
        
        struct ViewModel {
            let topicsList: TopicList?
        }
    }
    
    enum GetTagsData {
        struct Request {
        }
        
        struct Response {
            let tagsResponse: TagsResponse?
        }
        
        struct ViewModel {
            let tagsResponse: [TagsDetail]?
        }
    }
}
