//
//  MainFeedInteractor.swift
//  PantipFeed
//
//  Created by thanathip.kumnarai on 18/7/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFeedBusinessLogic {
    func doSomething(request: MainFeed.Something.Request)
}

protocol MainFeedDataStore {
    //var name: String { get set }
}

class MainFeedInteractor: MainFeedBusinessLogic, MainFeedDataStore {
    var presenter: MainFeedPresentationLogic?
    var worker: MainFeedWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: MainFeed.Something.Request)
    {
        worker = MainFeedWorker()
        worker?.doSomeWork()
        
        let response = MainFeed.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
