//
//  MainFeedPresenter.swift
//  PantipFeed
//
//  Created by thanathip.kumnarai on 18/7/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFeedPresentationLogic
{
    func presentSomething(response: MainFeed.Something.Response)
}

class MainFeedPresenter: MainFeedPresentationLogic
{
    weak var viewController: MainFeedDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: MainFeed.Something.Response)
    {
        let viewModel = MainFeed.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
