//
//  MainFeedWorker.swift
//  PantipFeed
//
//  Created by thanathip.kumnarai on 18/7/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainFeedWorker
{
    func doSomeWork()
    {
    }
}
