//
//  MainFeedPresenter.swift
//  PantipFeed
//
//  Created by thanathip.kumnarai on 18/7/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFeedPresentationLogic {
    func presentTopic(response: MainFeed.GetTopicData.Response)
    func presentTag(response: MainFeed.GetTagsData.Response)
    func presentError(errorMessage: String)
}

class MainFeedPresenter: MainFeedPresentationLogic
{
    weak var viewController: MainFeedDisplayLogic?

    func presentTopic(response: MainFeed.GetTopicData.Response) {
        viewController?.displayTopicData(viewModel: MainFeed.GetTopicData.ViewModel(topicsList: response.topicsResponse))
    }
    
    func presentTag(response: MainFeed.GetTagsData.Response) {
        viewController?.displayTagsData(viewModel: MainFeed.GetTagsData.ViewModel(tagsResponse: response.tagsResponse?.data ?? []))
    }
    
    func presentError(errorMessage: String) {
        self.viewController?.displayError(errorMessage: errorMessage)
    }
}
